/**
 * Created on 2023/8/26
 * Auth: wuxiaobo
 */
export class AppPage{
  static readonly pageTextDemo: string = 'pages/home/ui/TextDemo';
  static readonly pageButtonDemo: string = 'pages/home/ui/ButtonDemo';
  static readonly pageImageDemo: string = 'pages/home/ui/ImageDemo';
  static readonly pageTextInputDemo: string = 'pages/home/ui/TextInputDemo';
  static readonly pageProgressDemo: string = 'pages/home/ui/ProgressDemo';
  static readonly pagePickerDemo: string = "pages/home/ui/PickerDemo";
  static readonly pageQrCodeDemo: string = "pages/home/ui/QRCodeDemo";
  static readonly pageToggleDemo: string = "pages/home/ui/ToggleDemo";
}