/**
 * Created on 2023/8/26
 * Auth: wuxiaobo
 */
export class AppPage{
  static readonly pageTextDemo: string = 'pages/home/ui/TextDemo';
  static readonly pageButtonDemo: string = 'pages/home/ui/ButtonDemo';
  static readonly pageImageDemo: string = 'pages/home/ui/ImageDemo';
  static readonly pageTextInputDemo: string = 'pages/home/ui/TextInputDemo';
  static readonly pageProgressDemo: string = 'pages/home/ui/ProgressDemo';
  static readonly pagePickerDemo: string = "pages/home/ui/PickerDemo";
  static readonly pageQrCodeDemo: string = "pages/home/ui/QRCodeDemo";
  static readonly pageToggleDemo: string = "pages/home/ui/ToggleDemo";
  static readonly pageSlideDemo: string = "pages/home/ui/SlideDemo";
  static readonly pageRatingDemo: string = "pages/home/ui/RatingDemo";
  static readonly pageSideBarDemo: string = "pages/home/ui/SideBarDemo";
  static readonly pageBadgeDemo: string = "pages/home/ui/BadgeDemo";
  static readonly pageRelativeDemo: string = "pages/home/ui/RelativeDemo";
  static readonly pageScrollDemo: string = "pages/home/ui/ScrollDemo";
}